import { Inter, Montserrat, PT_Serif, Poppins } from "next/font/google";
import { Montserrat_Subrayada } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const montserrat_subrayada = Montserrat_Subrayada({
  weight: "700",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});
const pt_serif = PT_Serif({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "made with love",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pt_serif.className}>{children}</body>
    </html>
  );
}
